# Generated by Django 4.2.11 on 2025-05-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('project_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('app', 'Django'), ('product', 'Django REST API'), ('branding', 'Telegram bot')], max_length=50)),
            ],
        ),
    ]
