# Generated by Django 5.2 on 2025-05-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactme'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactme',
            name='phone',
            field=models.CharField(default=1111, max_length=20),
            preserve_default=False,
        ),
    ]
